# Generated by Django 4.0.1 on 2022-02-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=300, verbose_name='고래밥'),
        ),
    ]
