version: '3.8'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn whaling.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: whaling.settings.prod
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  react:
    container_name: react
    build:
      context: ./config/react
      dockerfile: Dockerfile
    volumes:
      - /frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=devlopment
    ports:
      - "3000:3000"
    stdin_open: true

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - react

volumes:
  static:
  media: