version: '3.8'
services:

  web:
    container_name: web
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn whaling.wsgi:application --bind 0.0.0.0:8000
    environment:
      DJANGO_SETTINGS_MODULE: whaling.settings.prod
        - TZ=Asia/Seoul
    env_file:
      - .env
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    entrypoint:
      - sh
      - config/docker/entrypoint.prod.sh

  react:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm run build && npm run start"
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    environment:
      - TZ=Asia/Seoul
      - NODE_ENV=devlopment
    expose:
      - 3000
    stdin_open: true
    restart: always

  nginx:
    container_name: nginx
    build: ./config/nginx
    volumes:
      - static:/home/app/web/static
      - media:/home/app/web/media
      - ./frontend:/root
    environment:
      - TZ=Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - react

volumes:
  static:
  media: