# Generated by Django 4.0 on 2022-01-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_choice_choice_alter_choice_choice_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_admin_vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='total_participants',
            field=models.IntegerField(default=0, verbose_name='투표 참가자 수'),
        ),
    ]
