# Generated by Django 4.0 on 2022-01-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_coin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
