# Generated by Django 4.0 on 2022-01-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_delete_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('coin_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coin_krname', models.CharField(max_length=12, verbose_name='코인 한글 이름')),
                ('coin_name', models.CharField(max_length=30, verbose_name='코인 한글과 티커 합친 이름')),
                ('coin_image', models.URLField(verbose_name='코인 이미지 링크')),
            ],
        ),
    ]
