# Generated by Django 4.0 on 2022-01-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0006_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.BooleanField(verbose_name='유저의 선택'),
        ),
    ]
