# Generated by Django 4.0 on 2022-01-18 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0006_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='coin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vote.coin',
                                    verbose_name='투표를 생성할 코인의 종류'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.BooleanField(verbose_name='유저의 선택'),
        ),
    ]
