# Generated by Django 4.0 on 2022-01-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('vote', '0008_rename_coin_code_coin_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice',
            field=models.IntegerField(choices=[(1, 'yes'), (2, 'no')], null=True, verbose_name='유저의 선택'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='state',
            field=models.TextField(choices=[('ongoing', '진행 중인 투표'), ('finished', '완료된 투표'), ('tracked', '트래킹된 투표')],
                                   default='ongoing', verbose_name='투표 상태'),
        ),
    ]
