# Generated by Django 4.0 on 2022-01-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_alter_choice_choice_alter_vote_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='state',
            field=models.CharField(choices=[('ongoing', '진행 중인 투표'), ('finished', '완료된 투표'), ('tracked', '트래킹된 투표')], default='ongoing', max_length=10, verbose_name='투표 상태'),
        ),
    ]
