# Generated by Django 4.0.1 on 2022-01-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_alter_vote_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.coin', verbose_name='코인의 종류'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='range',
            field=models.PositiveIntegerField(verbose_name='예상 변동폭'),
        ),
    ]
