# Generated by Django 4.0.1 on 2022-01-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_alter_vote_coin_alter_vote_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at']},
        ),
    ]
