# Generated by Django 4.0.1 on 2022-01-29 17:41

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_alter_vote_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(default=account.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(default=account.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(default=account.models.get_current_time),
        ),
        migrations.AlterField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(default=account.models.get_current_time),
        ),
    ]
